### ISSUE TITLE
Add Ability to specify scaffold form field outputs/inputs

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels-cli#8]
with templating, we need a way to scaffold certain input/outputs (date fields, checkboxes) which have designated markup - i.e, bootstrap style markup; 

This would need a way of storing the current templating scheme (box.json maybe?) and then pulling the appropriate fields in that way.

**Comment by bpamiri** [comment]
I think we can achieve this with the new templates folder I added. Basically I moved a copy of the templates folder in the CLI into the framework. This folder gets added to the Base Template so it get pulled down and installed. By moving it out of the CLI and into the template it allows us to build a Bootstrap template, Bulma template, and perhaps a Tailwind template each with their own version of config/settings.cfm and CRUD template files since the markup for each may be drastically different. This also lets the user tune the templates for their personal preference, and then each time they use the CLI to generate something their own code will be used.
